spring:
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true

#  datasource:
#    url: jdbc:postgresql://localhost:5432/test321
#    username: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver
  cloud:
    function:
      definition: consumerBinding;processorBinding;producerBinding;writeToFile;
    stream:
      bindings:
        producerBinding-out-0:
          destination: processor-topic
        processorBinding-in-0:
          destination: processor-topic
        processorBinding-out-0:
          destination: consumer1-topic
          producer:
            partitionCount: 9
            partitionKeyExpression: headers.partitionKey
        writeToFile-in-0:
          destination: processor-topic
      kafka:
        binder:
          brokers:
            - localhost:9092
---

#db:
#  url: jdbc:postgresql://localhost:5432/backup
#  username: postgres
#  password: postgres
#  driver-class-name: org.postgresql.Driver
#  url2: jdbc:postgresql://localhost:5432/


